name = "ScanDir"
uuid = "af3a3400-1793-11ea-1d1f-a522511abb08"
authors = ["yha <yharel@campus.technion.ac.il>"]
version = "0.4.2"

[compat]
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
